apiVersion: v1
kind: Service
metadata:
  name: flow-service
  labels:
    name: flow-ms
spec:
  ports:
    - port: 3331
      name: flow-ms-port
      protocol: TCP
  selector:
    app: flow-ms
    id: '0'
  type: LoadBalancer
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: flow-ms0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flow-ms
      id: '0'
  template:
    metadata:
      labels:
        app: flow-ms
        id: '0'
    spec:
      containers:
        - name: flow-ms
          image: docker.io/sachinj4/flow-ms:0.0.1
