kind: Deployment
apiVersion: apps/v1
metadata:
  name: zookeeper-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-1
  template:
    metadata:
      labels:
        app: zookeeper-1
    spec:
      containers:
        - name: zoo1
          image: docker.io/bitnami/zookeeper:3
          ports:
            - containerPort: 2181
          env:
            - name: ZOOKEEPER_ID
              value: '1'
            - name: ZOOKEEPER_SERVER_1
              value: zoo1
            - name: ALLOW_ANONYMOUS_LOGIN
              value: 'yes'
---
apiVersion: v1
kind: Service
metadata:
  name: zoo1
  labels:
    app: zookeeper-1
spec:
  ports:
    - name: client
      port: 2181
      protocol: TCP
    - name: follower
      port: 2888
      protocol: TCP
    - name: leader
      port: 3888
      protocol: TCP
  selector:
    app: zookeeper-1
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  labels:
    name: kafka
spec:
  ports:
    - port: 9092
      name: kafka-port
      protocol: TCP
    - port: 19092
      name: kafka-port-int
      protocol: TCP
  selector:
    app: kafka
    id: '0'
  type: LoadBalancer
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka-broker0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
      id: '0'
  template:
    metadata:
      labels:
        app: kafka
        id: '0'
    spec:
      containers:
        - name: kafka
          image: docker.io/bitnami/kafka:2-debian-10
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_ADVERTISED_PORT
              value: '30718'
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: localhost:9092
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zoo1:2181
            - name: KAFKA_BROKER_ID
              value: '0'
            - name: KAFKA_CREATE_TOPICS
              value: admint-test:1:1
            - name: ALLOW_PLAINTEXT_LISTENER
              value: 'yes'
            - name: KAFKA_LISTENERS
              value: INTERNAL://0.0.0.0:19092,EXTERNAL://0.0.0.0:9092
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
            - name: KAFKA_ADVERTISED_LISTENERS
              value: EXTERNAL://localhost:9092,INTERNAL://kafka-service:19092
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: INTERNAL
